version: "3"
services:
  nextjs:
    image: ghcr.io/cookify-webapp/cookify-frontend:dev
    restart: unless-stopped
    container_name: "nextjs"
    env_file:
      - ./cookify-frontend/.env.development
    networks:
      - cookify-webapp
  nginx:
    build: ./cookify-frontend/nginx
    container_name: "nginx"
    ports:
      - "80:80"
    networks:
      - cookify-webapp
  expressjs:
    image: ghcr.io/cookify-webapp/cookify-backend:dev
    restart: unless-stopped
    container_name: "expressjs"
    env_file:
      - ./cookify-backend/.env.development
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - cookify-webapp
  mongodb:
    image: ghcr.io/cookify-webapp/cookify-database:dev
    container_name: "mongodb"
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - cookify-webapp
networks:
  cookify-webapp:
    driver: bridge
