version: "3"
services:
  nginx:
    build: ./nginx
    container_name: "nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/ckfyadmin/cookify-devops/cert:/cert/
networks:
  default:
    external:
      name: cookify-devops_cookify-webapp
