version: "3"
services:
  nginx:
    build: ./cookify-frontend/nginx
    container_name: "nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/cookifywebapp/.well-known/pki-validation:/usr/share/nginx/html/.well-known/pki-validation/
      - /home/cookifywebapp/cookify-devops/cert:/cert/
networks:
  default:
    external:
      name: cookify-devops_cookify-webapp
